- hosts: dhcp-server
  user: root
  vars:
    dhcp_server_ip: 192.168.137.131
  tasks:
  - mount: name=/media src=/dev/cdrom fstype=iso9660 state=mounted
  - copy: src=resource/etc/yum.repos.d/rhel.repo dest=/etc/yum.repos.d/rhel.repo

  - yum: name=dhcp state=installed
  - yum: name=syslinux state=installed
  - yum: name=tftp-server state=installed
  - yum: name=httpd state=installed
  - yum: name=libselinux-python state=installed

  - file: path=/var/lib/tftpboot.rhel6 state=directory
  - file: path=/var/lib/tftpboot.rhel6/syslinux state=directory
  - file: path=/var/lib/tftpboot state=absent
  - file: src=/var/lib/tftpboot.rhel6 path=/var/lib/tftpboot state=link
  - file: path=/var/www/html/rhel65 state=directory
  - file: src=/media path=/var/www/html/rhel65/image state=link

  - template: src=resource/etc/xinetd.d/tftp dest=/etc/xinetd.d/tftp
  - template: src=resource/etc/dhcp/dhcpd.conf dest=/etc/dhcp/dhcpd.conf
  - template: src=resource/var/www/html/rhel65/ks.cfg dest=/var/www/html/rhel65/ks.cfg
  - file: path=/var/www/html/rhel65/ks.cfg mode=0644 state=file

  - copy: src=/Volumes/RHEL_6.5\ x86_64/images/ dest=/var/lib/tftpboot.rhel6/
  - file: path=/var/lib/tftpboot.rhel6/pxelinux.cfg state=directory
  - command: cp /usr/share/syslinux/pxelinux.0 /var/lib/tftpboot.rhel6/pxelinux.0
  - command: cp /usr/share/syslinux/menu.c32 /var/lib/tftpboot.rhel6/syslinux/menu.c32
  - template: src=resource/var/lib/tftpboot.rhel6/pxelinux.cfg/default dest=/var/lib/tftpboot.rhel6/pxelinux.cfg/default

  - service: name=xinetd state=restarted
  - service: name=httpd state=restarted
  - service: name=dhcpd state=restarted
  - service: name=iptables state=stopped
